title: "SCUTSG Association"
email: "your-email@example.com"
description: >- 
  Official website of SCUTSG Association.
baseurl: ""
url: "https://scutsg.github.io"
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-archives
  - jekyll-include-cache

author:
  name: "Your SCUT Name"
  avatar: "/assets/images/profile.jpg"

collections:
  story:
    output: true
    permalink: /story/:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: "story"
    values:
      layout: single

footer:
  links: []

feed:
  icon: false
