title: "华南理工大学新加坡校友会"
description: >- 
  South China University of Technology Alumni Association (Singapore)
baseurl: ""
url: "https://scutsg.github.io"
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-archives
  - jekyll-include-cache

author:
  name: "华南理工大学<br>新加坡校友会"
  avatar: "/assets/images/profile.jpg"

collections:
  story:
    output: true
    permalink: /story/:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: "story"
    values:
      layout: single
      author_profile: true

footer:
  links: []

feed:
  icon: false
